[ADD] AppointmentListView & AppointmentDetailView to view all information about appointments
jhwang0801/PuzzleAI-VOIDOC-Back pull request #13
Opened 2022-07-05 07:27 UTC by choiboii

## :: 최근 작업 주제
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 
### - AppointmentListView and AppointmentDetailView
    - Gather data and present in list view
    - Dates are formatted for better presentation for front-end implementation
    - ListView shows the info and people of appointment
    - DetailView shows the details and images of appointment

<br />

## :: 테스트 코드 결과
<img width="540" alt="list_detail_view_test_results" src="https://user-images.githubusercontent.com/83613067/177273092-0cc73cbd-e420-49c1-ae90-251a1e6c4c6e.PNG">

2022-07-05 08:12 UTC, jasonkang14 requested changes

2022-07-05 08:12 UTC, jasonkang14 commented on users/tests.py
> +from users.utils  import generate_jwt
제거된 줄이 더 최신 코드인데 확인 부탁 드립니다.

2022-07-05 08:12 UTC, jasonkang14 commented on users/utils.py
> -class Validation:
`class`를 사용한 코드가 더 최신 코드입니다. 재승님과 확인 부탁드립니다

2022-07-05 08:12 UTC, jasonkang14 commented on users/views.py
> +class SignUpView(View):
여기도 `Validation` class 상속이 더 최근 코드라서, 재승님과 확인하시고 수정해주세요

2022-07-05 08:38 UTC, choiboii commented
I resolved the conflicts manually, and so now the branch should be updated and corrected. Please check one more time. Thank you!

2022-07-05 12:17 UTC, jasonkang14 commented on appointments/views.py
> +            appointment = Appointment.objects.get(userappointment__patient_id=request.user.id, userappointment__appointment_id=appointment_id)
`Appointment.objects.get(id=appointment_id)`로는 조회가 불가능한가요?

2022-07-05 12:18 UTC, jasonkang14 commented
conflict를 한 번 더 확인해주세요!

2022-07-06 01:19 UTC, jasonkang14 approved these changes
LGTM

2022-07-06 01:19 UTC, merged