[ADD] 의사 진료 가능 일자, 시간 출력 기능 추가 (ADD: WorkingDay, WorkingTime View)
jhwang0801/PuzzleAI-VOIDOC-Back pull request #7
Opened 2022-06-29 04:02 UTC by jhwang0801

## :: 최근 작업 주제
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 
### - 의사가 진료 가능한 일자 출력
### - 선택 일자의 예약가능한 시간 출력
### - 이미 예약되어있는 시간 출력

<br />

## :: 테스트 코드 결과
<img width="588" alt="image" src="https://user-images.githubusercontent.com/75832544/176347695-59ef9b31-04b1-4dd6-a267-98f2d5f5e484.png">

## :: Postman 결과
#### (1) 의사 `진료 가능 일자` 출력 (선택한 년도, 월에 따라 변경)
<img width="614" alt="스크린샷 2022-06-29 오후 12 41 32" src="https://user-images.githubusercontent.com/75832544/176347963-6a4c2018-e46a-4769-94eb-394a6083ba88.png">

#### (2) 선택 일자의 `예약가능 시간` & `예약된 시간` 출력 (선택한 년도, 월, 일에 따라 변경)
<img width="640" alt="스크린샷 2022-06-29 오후 12 41 42" src="https://user-images.githubusercontent.com/75832544/176347907-7a43cad0-c94d-491b-9453-f136d59d3fba.png">

#### (3) 당일 예약 시도 시 에러 출력
<img width="644" alt="스크린샷 2022-06-29 오후 12 41 48" src="https://user-images.githubusercontent.com/75832544/176348472-5f702aea-434d-4a81-b47e-63dbd93c3a3c.png">

#### (4) 이전 날짜 예약 시도 시 에러 출력
<img width="672" alt="스크린샷 2022-06-29 오후 12 41 56" src="https://user-images.githubusercontent.com/75832544/176348621-3092fb37-0f3b-495d-a7db-a77f5208eea4.png">

2022-06-29 04:49 UTC, jiyeon-kim-ds commented on appointments/views.py
> +            return JsonResponse({'message' : 'NOT_AVAILABLE_ON_THE_DAY_OF_MAKING_AN_APPOINTMENT'}, status=403)
status는 403보다 400이 더 적절해보입니다! [link](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/400)

2022-06-29 04:50 UTC, jiyeon-kim-ds commented on appointments/views.py
> +            return JsonResponse({'message' : 'NOT_AVAILABLE_ON_THE_DAY_OF_MAKING_AN_APPOINTMENT'}, status=403)
status는 403보다 400이 더 적절해보입니다! [link](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/400)

2022-06-29 04:59 UTC, jhwang0801 commented on appointments/views.py
> +            return JsonResponse({'message' : 'NOT_AVAILABLE_ON_THE_DAY_OF_MAKING_AN_APPOINTMENT'}, status=403)
리뷰 감사합니다~

`403 forbidden` 자체가 웹 브라우저에서 열려고 하는 웹페이지나 리소스가 액세스 불가능한 리소스인 경우 발생한다 생각했는데,
"authorization" 과 "authenticate" 에 관련된 문제일 때 발생하는 거였네요.

수정해서 반영하도록 하겠습니다!

2022-06-29 05:30 UTC, jhwang0801 commented on appointments/views.py
> +            return JsonResponse({'message' : 'NOT_AVAILABLE_ON_THE_DAY_OF_MAKING_AN_APPOINTMENT'}, status=403)
수정 반영하였습니다~ 감사합니다!

2022-06-29 06:58 UTC, jasonkang14 requested changes

2022-06-29 06:58 UTC, jasonkang14 commented on appointments/views.py
> +from django.db.models           import Q
같은 곳에서 import되니 하나로 합치는 편이 좋을 것 같습니다
```python
from django.db.models import CharField, Value as V, Q
```

2022-06-29 06:58 UTC, jasonkang14 commented on appointments/views.py
> +        not_day_off = [working_day.date.day for working_day in WorkingDay.objects.filter(doctor_id=doctor_id, date__year = year, date__month = month)]
적절하게 잘 섞어서 쓰시는군요 💯

2022-06-29 06:58 UTC, jasonkang14 commented on appointments/views.py
> +        if selected_date < current:
`selected_date`를 `.strptime()`, `strftime()`사용하지 않고  `datetime.now()`하고만 비교해도 되지 않나요? 
조건비교 이후에 `current`를 사용하는 곳이 없어서 굳이 format을 맞추지 않아도 될 것 같습니다

2022-06-29 06:58 UTC, jasonkang14 commented on appointments/views.py
> +        q = Q()
👍

2022-06-29 06:58 UTC, jasonkang14 commented on appointments/views.py
> +        q.add(Q(userappointment__doctor_id = doctor_id, date=selected_date, state_id = 1), q.AND)
`doctor_id`가 중복되니 `state_id`에만 `Q`를 사용해도 되지 않나요?

2022-06-29 06:58 UTC, jasonkang14 commented on users/tests.py
> +            'user_id'     : CustomUser.objects.get(is_doctor=False).id,
저번에 말씀 드렸던 부분인데 코드가 수정됐다고 나와서 다시 말씀 드립니다. 
같은 instance에 접근할 때는 [cache](https://docs.djangoproject.com/en/4.0/topics/db/optimization/#understand-cached-attributes)를 활용해주시는 편이 좋습니다.

2022-06-29 07:00 UTC, jhwang0801 commented on appointments/views.py
> +from django.db.models           import Q
넵 수정사항 반영하겠습니다.

2022-06-29 07:07 UTC, jhwang0801 commented on appointments/views.py
> +        if selected_date < current:
`datetime.now()`를 사용하게되면, 
`datetime.datetime(2022, 6, 29, 16, 1, 18, 946291)` 와 같이 `time`에 관련된 값까지 함께 포함이 되어있습니다.

조금 더 하단의 코드에 있는 선택한 날짜와 현재 날짜가 동일한지 비교하는 부분에서
`selected_date`는 `datetime.datetime(year, month, day, 0, 0)`의 형태이기 때문에
`if selected_date == current:`라는 해당 조건문 과정에서 동일한 format이 아니면 동일한 값이 들어오는지 비교가 불가능하여 `.strptime()`, `strftime()`을 사용해주었습니다.

2022-06-29 07:26 UTC, jhwang0801 commented on appointments/views.py
> +        q.add(Q(userappointment__doctor_id = doctor_id, date=selected_date, state_id = 1), q.AND)
위 코드에서 
`Q(userappointment__doctor_id = doctor_id, date=selected_date)`는 원하는 진료예약 일정만 출력하기 위하여 **꼭 필요**합니다.

원하는 진료예약 일정만을 출력하려면 총 3가지의 조건이 모두 갖추어져야합니다.
1. 어떤 의사와의 예약인지 확인 (`userappointment__doctor_id = doctor_id`) &
2. 선택한 날짜에 예약된 일정인지 확인 (`date = selected_date`) &
3. 예약된 일정이 어떤 상태인지 확인 (`state_id = 1 or 2`)

만약 `state_id`에만 Q를 사용한다면,
DB 내에 저장되어 있는 모든 예약 일정들 중 `state_id`가 1과 2인 일정이 모두 출력됩니다.

2022-06-29 07:30 UTC, jhwang0801 commented on users/tests.py
> +            'user_id'     : CustomUser.objects.get(is_doctor=False).id,
수정해서 다시 push하도록 하겠습니다!!

2022-06-29 08:13 UTC, jhwang0801 commented on appointments/views.py
> +        if selected_date < current:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/75832544/176386597-2adee730-6f31-4e1c-878c-b61b9d6d658a.png">

2022-06-29 10:02 UTC, jhwang0801 commented on appointments/views.py
> +        if selected_date < current:
해당 부분을 아까 말씀해주신 대로,
선택일자와 현재시간이 동일한 조건문 앞에 새로 변수를 지정해서 해보았으나 실패했습니다.

이유는 `datetime.now()`를 사용할 경우, 현재날짜에 항상 시간까지 합쳐져서 출력되기 때문에
선택일자(`datetime(year,month,day)`)보다 항상 클 수 밖에 없습니다.

따라서 위의 조건문인 `if selected_date < current`에 항상 걸려 먼저 return이 되어버리게 됩니다.

2022-06-30 01:20 UTC, jhwang0801 commented on appointments/views.py
> +        q.add(Q(userappointment__doctor_id = doctor_id, date=selected_date, state_id = 1), q.AND)
```python
q = Q()
q.add(Q(userappointment__doctor_id = doctor_id), q.AND)
q.add(Q(date = selected_date), q.AND)
q.add(Q(state_id = 1) | Q(state_id = 2), q.AND)
appointments = Appointment.objects.filter(q)
```

위와 같은 코드로 수정하였습니다.

2022-06-30 01:39 UTC, jasonkang14 approved these changes
LGTM

2022-06-30 01:39 UTC, merged